services:
  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_en2a-users:latest
    ports:
      - "3000:3000"
    environment:
      - GAMEMANAGER_URL=http://game_manager:5000
      - AUTH_URL=http://auth-engine:4001
      - GAMEY_URL=http://gamey:4000 
    depends_on:
      - auth-engine
      - gamey 
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
        - VITE_GAMEMANAGER_URL=http://localhost:5000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_en2a-webapp:latest
    ports:
      - "80:80"
    environment:
      - GAMEMANAGER_URL=http://game_manager:5000
    depends_on:
      - users
      - game_manager
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_en2a-gamey:latest
    expose:
      - "4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

  game_manager:
    build: ./game_manager
    container_name: game_manager
    image: ghcr.io/arquisoft/yovi_en2a-gamemanager:latest
    expose:
      - "5000"
    environment:
      - PORT=5000
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
      - GAMEY=gamey
    depends_on:
      - redis_db
      - gamey
    networks:
      - monitor-net

  redis_db:
    image: redis:alpine
    container_name: redis_db
    expose:
      - "6379"
    networks:
      - monitor-net
    volumes:
      - redis_data:/data

  auth-engine:
    build: ./userAuthentification
    image: ghcr.io/arquisoft/yovi_en2a-auth-engine:latest
    container_name: userAuthentification
    expose:
      - "4001"
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  redis_data: