sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_en2a
sonar.projectName=yovi_en2a

sonar.sources=webapp/src,users,gamey/src, userAuthentification/src
sonar.tests=webapp/src,users/__tests__,gamey/src, userAuthentification/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.js
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,users/coverage/lcov.info
sonar.rust.lcov.reportPaths=gamey/lcov.info
sonar.coverage.exclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.spec.ts,**/*.spec.tsx,**/*.spec.js
